export const data = [
  {
    role: 'front-end developer',
    fullname: 'Bui Dinh Loc',
    avatar: process.env.PUBLIC_URL + '/images/avatar.jpg',
    dateOfBirth: '06/03/2001',
    address: 'HMC city, Viet Nam',
    phone: '0969819201',
    mail: 'dinhloc334@gmail.com',
    githubLink: '#',
    facebookLink: 'https://www.facebook.com/dinhlocpisces/',
    intagramLink: '#',
    twitterLink: '#',
    youtubeLink: '#',
  },
  {
    role: 'back-end developer',
    fullname: 'Nguyen Phung Le Luan',
    avatar: process.env.PUBLIC_URL + '/images/dev_be.jpg',
    dateOfBirth: '01/07/2001',
    address: 'HMC city, Viet Nam',
    phone: '0966053416',
    mail: 'leenguyen1721@gmail.com',
    githubLink: '#',
    facebookLink: '#',
    intagramLink: '#',
    twitterLink: '#',
    youtubeLink: '#',
  },
];
