const routes = {
  notFound: '*',
  home: '/',
  login: '/login',
  contact: '/contact',
  signup: '/register',
  profile: '/profile/:nickname',
  forgetPassword: '/forgetpassword',
  cart: '/cart',
  wishlist: '/wishlist',
  about: '/about',
  checkout: '/checkout',
  product: '/product/:productId',
  products: '/products',
  allProduct: '/products/q=:keyword',
  allProductWithDefaultPagination: '/products/q=:keyword/page=',
  allProductWithPagination: '/products/q=:keyword/page=:page',
  category: '/category',
  categoryWithGenre: '/category/:genre',
  categoryWithDefaultPagination: '/category/:genre/page=',
  categoryWithPagination: '/category/:genre/page=:page',
  search: '/search/q=:keyword',
  searchWithDefaultPagination: '/search/q=:keyword/page=',
  searchWithPagination: '/search/q=:keyword/page=:page',
  community: '/community',
};

export default routes;
